name: Swift CI

on:
  push:
    branches: [ "master", "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Swift
      if: runner.os == 'Linux'
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Build
      run: swift build -c release

    - name: Run tests
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          swift test --enable-code-coverage
        else
          swift test
        fi

    - name: Upload Linux Artifact
      if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: cdd-swift-linux
        path: .build/release/cdd-swift

    - name: Upload macOS Artifact
      if: runner.os == 'macOS' && startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: cdd-swift-macos
        path: .build/release/cdd-swift

  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"

    - name: Install SwiftWasm
      run: |
        swift sdk install https://github.com/swiftwasm/swift/releases/download/swift-wasm-6.0.3-RELEASE/swift-wasm-6.0.3-RELEASE-wasm32-unknown-wasi.artifactbundle.zip --checksum 31d3585b06dd92de390bacc18527801480163188cd7473f492956b5e213a8618
        swift build --swift-sdk wasm32-unknown-wasi -c release

    - name: Upload WASM Artifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: cdd-swift-wasm
        path: .build/wasm32-unknown-wasi/release/cdd-swift-cli

  release:
    needs: [build, build-wasm]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Rename binaries
        run: |
          mv artifacts/cdd-swift-linux/cdd-swift cdd-swift-linux
          mv artifacts/cdd-swift-macos/cdd-swift cdd-swift-macos
          mv artifacts/cdd-swift-wasm/cdd-swift-cli cdd-swift.wasm

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cdd-swift-linux
            cdd-swift-macos
            cdd-swift.wasm
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
